# Generated by Django 5.0.6 on 2024-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses_monitoring",
            "0003_alter_bankconnection_user_alter_expense_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="timestamp",
            field=models.BigIntegerField(default=1715636251.63501),
        ),
    ]
