# Generated by Django 5.0.6 on 2024-05-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses_monitoring", "0005_alter_expense_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="account",
            name="currencyCode",
        ),
        migrations.RemoveField(
            model_name="account",
            name="iban",
        ),
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="account",
            name="maskedPan",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="expense",
            name="timestamp",
            field=models.BigIntegerField(default=1715893972.143462),
        ),
    ]
