version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
    command: gunicorn --log-level info --workers 3 --timeout 1200 --bind :8000 exp_d.wsgi:application

volumes:
  app:
  data:
  staticfiles:
